### ISSUE TITLE
Example from README doesn't seem to be working

### ISSUE THREAD

**Issue by nbeloglazov** [Lambda-X/replumb#146]
Hi 

I'm trying to run example from README. But it doesn't compile because `replumb.browser.io` is not present in the library. I checked source of replumb-0.1.4.jar and it is indeed not there. Looking at [project.clj](https://github.com/Lambda-X/replumb/blob/master/project.clj#L21) it seems like `src/browser` folder is used as source only in dev mode (locally) but not gets included into packaged library. Could you take a look?

Thanks,
Nikita

**Comment by arichiardi** [comment]
It is unfortunately not possible to include io parts in the same package without breaking. There are two (or more) io target and they are exclusive (browser, node). If I had included one, the other would have not be compiled correctly.

The only solution to this are reader conditionals. But custom reader conditionals did not yet land in neither Cuojure nor ClojureScript. A custom reader conditional tagged `nodejs` would solve.

In the meantime, feel free to copy over those namespaces, following along checking the `repl-demo` folder.

**Comment by nbeloglazov** [comment]
I see. Should example/instructions in README be also fixed? Right now README states that includeing replumb as dependency is sufficient to run example which is not entirely true.

**Comment by arichiardi** [comment]
I will better specify (hopefully) that, thanks a lot!

**Comment by arichiardi** [comment]
Done f34d9e3db1fd4cddd25b00d4365fb546140624a3

**Comment by nbeloglazov** [comment]
Thanks!

**Comment by arichiardi** [comment]
Thank you for pointing it out!
