### ISSUE TITLE
Running Replumb as Node.js lib

### ISSUE THREAD

**Issue by roman01la** [Lambda-X/replumb#172]
Hi. Thanks for such easy to use lib! I'm rebuilding ClojureScript processor for JS Bin with Replumb and I have an issue when trying to evaluate cljs code by calling Replumb function imported from build output file.

Here's my cljs file:

```clojure
(ns jsbin-cljs.core
  (:require [replumb.core :as replumb]
            [replumb.nodejs :refer [init-fn!]]))

(defn ^:export eval [src-str callback]
  (replumb/read-eval-call {:verbose false
                           :warning-as-error false
                           :target :nodejs
                           :context :statement
                           :init-fns [init-fn!]}
                          (fn [{:keys [success? error value]}]
                           (if success?
                             (callback nil value)
                             (callback (.. error -cause))))
                          src-str))

(set! *main-cli-fn* identity)
```

With that I'm running the following test script in Node.js. You can see the output for both evaluation calls as comments.

```js
var c = require('./out/jsbin-cljs');

c.jsbin_cljs.core.eval(
`(defn r [v]
  (->> v (map inc) (filter odd?)))
(def v [1 2 3 4 5 56])
(r v)`,
(err, v) => console.log(err, v)); // undefined undefined

c.jsbin_cljs.core.eval(
`(defn r [v]
  (->> v (map inc) (filter odd?)))
(def v [1 2 3 4 5 56])
(r v)`,
(err, v) => console.log(err, v)); // [TypeError: Cannot set property 'r' of undefined] undefined
```

I have two questions:
- Why it doesn't return the result of the last expression?
- Is there something wrong is going on with a namespace when evaluating the second time?

Thanks!

**Comment by arichiardi** [comment]
I would say that first of all you don't have to use `init-fn` explicitly like that, but use `replumb.core/options` and `assoc` the `:warning-as-error false` and `:context :statement`. Example [here](https://github.com/Lambda-X/replumb/blob/master/repl-demo/node/cljs/nodejs_repl/core.cljs#L52). The "client" code looks good to me.

**Comment by roman01la** [comment]
I've just build node-repl example with simple optimisations and I'm getting the following error when trying to evaluate any expression: `Cannot set property 'user' of undefined`

**Comment by arichiardi** [comment]
Yes `node` and `browser` mode have some problems with `:simple` optimization at the moment, depends on what you want to do, but it would definitely need some PR.

**Comment by roman01la** [comment]
Ok, thank you anyway. I'm going to close the issue then.

**Comment by arichiardi** [comment]
:+1:

**Comment by arichiardi** [comment]
@roman01la I (hopefully) fixed the problem with `:simple` and Node.JS. It looks better now (no more error described up here). Can you give it a try?
