### ISSUE TITLE
How to require macros?

### ISSUE THREAD

**Issue by viebel** [Lambda-X/replumb#173]
Could you provide code snippet for how could I evaluate a namespace that requires macros?

**Comment by arichiardi** [comment]
Thanks for inquiring about `replumb`! It would be better though if we keep GitHub for issues only. You can ping me any time on Slack or ask on #clojurescript on Clojurians for this kind of question. A lot more people can provide answers there.
About this particular question, you can check the tests and be sure that the macro `.clj` is on your `:src-paths`. Also, [Mike Fikes](http://blog.fikesfarm.com/archives.html) has written a lot of about macros in bootstrapped and not.
If something does not work, well, feel free to open an issue, ideally with a small use case/example.
I am going to close this one for now.

**Comment by viebel** [comment]
@arichiardi sure. What's your name on slack?
