### ISSUE TITLE
static-fns option is not exposed by read-eval-call

### ISSUE THREAD

**Issue by viebel** [Lambda-X/replumb#180]

**Comment by arichiardi** [comment]
Thanks for reporting, I will add it asap

**Comment by viebel** [comment]
thx

**Comment by viebel** [comment]
I see the fix in master.
When do you plan to deploy it?

**Comment by arichiardi** [comment]
It should already be deployed as `0.2.2-SNAPSHOT` and I am planning a release at the end of this week

**Comment by arichiardi** [comment]
BTW please let me know if it works for you

**Comment by viebel** [comment]
It wors fine. Thanks.

BTW, I found an interesting edge case that breaks evaluation with :static-fns true.

[http://tinyurl.com/klipse-break-static-fns]( http://tinyurl.com/klipse-break-static-fns)
In KLIPSE, it works fine (I have not yet deployed support for static-fns evaluation).
But If you evaluate the js transpiled code in the console, it breaks!!!
