### ISSUE TITLE
Issues with clojurescript 1.9.198

### ISSUE THREAD

**Issue by viebel** [Lambda-X/replumb#195]
I’m having the issue you mentioned on #cljs-dev https://clojurians.slack.com/archives/cljs-dev/p1470946655000653  on klipse
```
cljs.user=> (require '[clojure.string :refer [trim]])
No such namespace: cljs.string, could not locate cljs/string.cljs, cljs/string.cljc, or Closure namespace "cljs.string"
```
Is it a bug on replumb?

**Comment by arichiardi** [comment]
I still need more time for investigating what is going on. It can be that in some way the new version changed some replumb behavior.

**Comment by viebel** [comment]
OK. For the moment, it prevents me from upgrading Klipse to 1.9.198

**Comment by arichiardi** [comment]
It looks like: `.../replumb/dev-resources/private/node/js/compiled/out/cljs/string.js` is not there anymore when it is compiled

**Comment by viebel** [comment]
1. Is it related to `replumb.load/loaded-js-set`? 
2. It would me nice to make it configurable: sometimes it is better to reload everything.

**Comment by arichiardi** [comment]
I thought about that, but is not, PR more than welcome on the topic, I am still check cljs source to see what changed.

On August 14, 2016 11:08:56 AM PDT, Yehonathan Sharvit <notifications@github.com> wrote:
>1. Is it related to `replumb.load/loaded-js-set`? 
>2. It would me nice to make it configurable: sometimes it is better to
>reload everything.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Lambda-X/replumb/issues/195#issuecomment-239687629

-ar

**Comment by viebel** [comment]
Will try to create a PR - but not before next week.
Keep me in the loop when you find (and solve) the issue.

Good luck!

**Comment by arichiardi** [comment]
@viebel replumb `0.2.4-SNAPSHOT` is deployed for cljs `1.9.198`, I am going to wait for a release as David said he will release another version soon with some fixes.

**Comment by viebel** [comment]
Thanks. It works fine now.  Both `clojure.string` and `:rename`.

Take a look here: http://viebel.github.io/klipse/examples/clojure-demo.html

**Comment by arichiardi** [comment]
Btw you could also contribute (yeah I know I am pushing :smihttps://github.com/Lambda-X/replumb/commit/1cceab7a8a26820c4d7cab823350d23ac8afb70f#diff-f100da5bcf7b16c68c163ed0d084056dL320le some example back to the test

**Comment by arichiardi** [comment]
By the way you can also contribute (I know I am pushing :smile:) back to the test if you'd like, the test macro is pretty easy to use, see changes here: https://github.com/Lambda-X/replumb/commit/1cceab7a8a26820c4d7cab823350d23ac8afb70f#diff-f100da5bcf7b16c68c163ed0d084056dL320

The things with the underline are provided withing the macro for the test to use, for example `_res_` is the result of the evaluation.

I alto added a section on how to start the dev environment with figwheel in the readme: https://github.com/Lambda-X/replumb/commit/12ae67a58638dcb9708048da8d59ecf77b9fef21#diff-04c6e90faac2675aa89e2176d2eec7d8L207
