### ISSUE TITLE
Comparison for self-require

### ISSUE THREAD

**Issue by mfikes** [Lambda-X/replumb#202]
See https://github.com/Lambda-X/replumb/blob/3c22fc32ee96a777c610ebb849fc5d44e1f93415/src/cljs/replumb/repl.cljs#L626

`:kind` should be `kind`

Similar to https://github.com/mfikes/planck/pull/360

**Comment by arichiardi** [comment]
Thanks Mike!

**Comment by arichiardi** [comment]
Would be great to add tests here of what a self-require is btw ;) I took this directly from Planck unashamedly, without here checking :blush:
