### ISSUE TITLE
Travis test results are weird

### ISSUE THREAD

**Issue by arichiardi** [Lambda-X/replumb#72]
Same number of tests for both `phantom` and `node` -> `Ran 22 tests containing 156 assertions.`:

```
$ lein2 do test-phantom*, test-node*

;; ======================================================================

;; Testing with Phantom:

Testing replumb.load-test

Testing replumb.require-test

Testing replumb.repl-test

(foo.core/hello (+ 2 3))

(hello (+ 2 3))

Testing replumb.common-test

Testing replumb.core-test

Testing replumb.options-test

Ran 22 tests containing 156 assertions.

0 failures, 0 errors.

Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///tmp/phantom114960521965219349.js. Domains, protocols and ports must match.

Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///tmp/phantom114960521965219349.js. Domains, protocols and ports must match.

;; ======================================================================

;; Testing with Node:

Testing replumb.load-test

Testing replumb.require-test

Testing replumb.repl-test

(foo.core/hello (+ 2 3))

(hello (+ 2 3))

Testing replumb.common-test

Testing replumb.core-test

Testing replumb.options-test

Ran 22 tests containing 156 assertions.

0 failures, 0 errors.
```

**Comment by arichiardi** [comment]
Maybe the Node.js is bugged? We need to check it with `node -v` and in case install it: https://github.com/bensu/doo#node

**Comment by arichiardi** [comment]
I also already checked with only `lein node-test` and it "Ran 22 tests containing 156 assertions."

**Comment by arichiardi** [comment]
To clarify, the tests are running, otherwise @tomasz-biernacki [last patch](https://github.com/ScalaConsultants/replumb/commit/d5e280d9ff24aa3c5baed108cc1406ab119ffb60) would be all green. It is a display/output issue only.

**Comment by arichiardi** [comment]
Wrong Node.js version indeed:

```
$ phantomjs -v
1.9.8
$ node -v
v0.10.36
```

**Comment by tomasz-biernacki** [comment]
Is this the version on the CI server or your local?

**Comment by arichiardi** [comment]
On Travis

**Comment by arichiardi** [comment]
Build without my `browser-test` builds section:
https://travis-ci.org/ScalaConsultants/replumb/builds/96525991

Build with it re-added:
https://travis-ci.org/ScalaConsultants/replumb/builds/96526301

Very weird or I have not understood how build profile work, it looks like the `require-test` in `src/browser/` gets added (and overrides) the one in `src/node` ... little problem...with don't have `src/browser` in the `:source-paths` key for `node-test`...

**Comment by arichiardi** [comment]
It looks like a `doo` problem.

**Comment by arichiardi** [comment]
It is partially fixed by actually renaming the files so that the namespace does not collide (f77fcea335c98984f5b699c0249f51167706ccbb).

**Comment by arichiardi** [comment]
Solved upstream with https://github.com/bensu/doo/commit/6e062c889ce13be3406d15fffa983a0d4444ddb9
