### ISSUE TITLE
":as" in ":require-macros" does not work - solved by CLJS-1521

### ISSUE THREAD

**Issue by tomasz-biernacki** [Lambda-X/replumb#90]
```
cljs.user=> (ns my.namespace (:require-macros [foo.bar.baz :as f]))
nil
my.namespace=> (f/mul-baz 12 20)
ERROR - f is not defined
```
see also [jira issue](http://dev.clojure.org/jira/browse/CLJS-1449) and [related failing test in replumb](https://github.com/ScalaConsultants/replumb/pull/106/files#diff-0c8062e850c7b0a02356a375c9130ef8R354)

**Comment by arichiardi** [comment]
@tomasz-biernacki, is there a (commented) test for this?

**Comment by tomasz-biernacki** [comment]
@arichiardi I will link to it but I'm investigating because this doesn't work in `1.7.202`.

**Comment by arichiardi** [comment]
ok, then please put also the label back, I opted to differentiate so that we know what we are looking at the issue list.

**Comment by tomasz-biernacki** [comment]
Not working in `1.7.202`.
```
cljs.user=> (ns my.namespace (:require-macros [foo.bar.baz :as f]))
nil
my.namespace=> (f/mul-baz 12 20)
ERROR - f is not defined
```

**Comment by arichiardi** [comment]
:+1:

**Comment by arichiardi** [comment]
Applying patch [CLJS-1521](http://dev.clojure.org/jira/browse/CLJS-1521) passes the previous test with alias:

```
cljs.user=> (ns my.namespace (:require-macros [foo.bar.baz :as f]))
nil
my.namespace=> (f/mul-baz 12 20)
240
```

**Comment by tomasz-biernacki** [comment]
Confirmed :+1:
